name: Continuous Learning Pipeline

on:
  schedule:
    - cron: '0 1 * * *'  # Runs every day at 1 AM

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./Data_Science/Continuous_Learning_Pipeline/requirements.txt
    
    - name: Run data ingestion script
      run: python ./Data_Science/Continuous_Learning_Pipeline/fetch_data.py
    
    - name: Run model retraining script
      run: python ./Data_Science/Continuous_Learning_Pipeline/retrain_model.py